<?

$ECLIENT_OK = 0;
$ECLIENT_ERR_PAY_WIN_EXIST = 1;
$ECLIENT_ERR_UNKNOWN = 2;
$ECLIENT_ERR_IDX_EXCEED = 3;


$ECLIENT_STATUS_LOGIN = "login";
$ECLIENT_STATUS_LOGOFF = "logoff";

$ECLIENT_STATUS_PREPAY = "prepay";
$ECLIENT_STATUS_PAING  = "paing";
$ECLIENT_STATUS_PAYED  = "payed";
$ECLIENT_STATUS_PAY_ERROR = "pay_error";

$ECLIENT_STATUS_PREADD = "preadd";
$ECLIENT_STATUS_ADDING = "adding";
$ECLIENT_STATUS_ADDED  = "added";
$ECLIENT_STATUS_ADD_ERROR = "add_error";
$ECLIENT_STATUS_FORCEEXIT = "forceexit";
